name: 'Generate Matrix Value Format'

inputs:
  element-list:
    description: 'List of elements'
    required: true
    type: string

outputs:
  formatted_values:
    description: "description"
    value: ${{ steps.format_value.outputs.formatted_values }}

runs:
  using: 'composite'
  steps:
    - name: Format Value
      id: format_value
      shell: bash
      run: |
        declare -a the_array=()
        IFS=', ' read -ra my_array <<< ${{ inputs.element-list }}
        jsonObject="["
        for ((i=0; i<${#my_array[@]}; i++)); do
          jsonObject+="\"${my_array[i]}\""
          if [[ $i -lt $(( ${#my_array[@]} - 1 )) ]]; then
            jsonObject+=","
          fi
        done
        jsonObject+="]"
        echo "formatted_values=${jsonObject}" >> $GITHUB_OUTPUT

    - name: Display
      shell: bash
      run: |
        echo ${{ steps.format_value.outputs.formatted_values }}