name: 'Builds and pushes a Spring Boot application Docker container'
description: 'Builds a Spring Boot application Docker container and pushes it to Google Container Registry. This workflow should be used for CI-CD workflows to update deployments that have been created with the Labs Cloud Helm Charts.'

inputs:
  gcloud-service-auth:
    required: false
    description: 'Credentials file for gcloud set up'
  project-id:
    required: true
    description: 'Google Cloud Project ID'
  deployment-name:
    required: true
    description: 'Name of the Google Cloud Project deployment'
  java-version:
    required: false
    description: 'Version of Java to use'
    default: 17

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      name: Install Java
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
    - run: echo "IMAGE_NAME=gcr.io/${{ inputs.project-id }}/${{ inputs.deployment-name }}" >> $GITHUB_OUTPUT
      shell: bash
      name: Generate the name of the docker image
      id: generate-image-name
    - uses: gradle/gradle-build-action@v2
      name: Build Docker Container
      with:
        arguments: |
          clean 
          bootBuildImage 
          --imageName=${{steps.generate-image-name.outputs.IMAGE_NAME}}:${{ github.sha }}
    - uses: google-github-actions/auth@v0
      name: Login to Google Cloud
      with:
        credentials_json: ${{ inputs.gcloud-service-auth }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        install_components: 'gke-gcloud-auth-plugin'
    - name: Authorize Docker push
      shell: bash
      run: gcloud auth configure-docker
    - name: Build and Push Container
      shell: bash
      run: |-
        docker push ${{steps.generate-image-name.outputs.IMAGE_NAME}}:${{ github.sha }}
        docker tag ${{ steps.generate-image-name.outputs.IMAGE_NAME }}:${{ github.sha }} ${{ steps.generate-image-name.outputs.IMAGE_NAME }}:latest
        docker push ${{steps.generate-image-name.outputs.IMAGE_NAME}}:latest