name: 'Build and deploy a Spring Boot application'
description: 'Builds and deploys a Spring Boot application to GKE. This workflow should be used for CI-CD workflows to update deployments that have been created with the Labs Cloud Helm Charts.'

inputs:
  gcloud-service-auth:
    required: false
    description: 'Credentials file for gcloud set up'
  project-id:
    required: true
    description: 'Google Cloud Project ID'
  deployment-name:
    required: true
    description: 'My Labs Cloud Name'
  deployment-region:
    required: false
    description: 'Google Cloud Deployment Region'
  deployment-zone:
    required: false
    description: 'Google Cloud Deployment Zone'
  cluster-name:
    required: true
    description: 'Google Cloud Cluster Name'
  deployment-environment:
    required: true
    description: 'Deployment Environment (ex: test, beta, prod, ...)'
  jvm-arguments:
    required: false
    description: 'Comma separated list of custom JVM arguments (ex: -Dsomething=value, -Dotherthing=value)'
  update-deployment:
    required: false
    description: 'Boolean indicating if the deployment should be updated along with the image push'
    default: 'true'
  artifactory-username:
    required: true
    description: 'The user name to access Labs Cloud artifacts from Artifactory'
  artifactory-password:
    required: true
    description: 'The password to access Labs Cloud artifacts from Artifactory'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      name: Checkout Source Code
    - uses: actions/setup-java@v3
      name: Install Java
      with:
        distribution: temurin
        java-version: 17
        cache: 'gradle'
    - uses: gradle/gradle-build-action@v2
      name: Install Gradle Wrapper
    - run: ./gradlew clean gnagCheck bootBuildImage -Partifactory_user=${{ inputs.artifactory-username }} -Partifactory_password=${{ ${{ inputs.artifactory-password }} -PimageTag=${{ github.sha }}
      name: Run Gnag and build Docker Container
      env:
        ARTIFACTORY_USER: ${{ inputs.artifactory-username }}
        ARTIFACTORY_PASSWORD: ${{ inputs.artifactory-password }}
    - uses: 'google-github-actions/auth@v0'
      name: Login to Google Cloud
      with:
        credentials_json: ${{ inputs.gcloud-service-auth }}
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: Authorize Docker push
      run: gcloud auth configure-docker
    - name: Build and Push Container
      run: |-
        docker push gcr.io/${{ inputs.project-id }}/${{ env.SERVICE }}:${{ github.sha }}
        docker push gcr.io/${{ inputs.project-id }}/${{ env.SERVICE }}:latest
    - name: Start the latest container
      run: |-
        kubectl set image deployment "${inputs.deployment-name}-${inputs.deployment-environment}" "${inputs.deployment-name}"="${HASH_TAG}" --all --record=true --namespace="${NAMESPACE}"