name: 'Build and deploy a Spring Boot application'
description: 'Builds and deploys a Spring Boot application to GKE. This workflow should be used for CI-CD workflows to update deployments that have been created with the Labs Cloud Helm Charts.'

inputs:
  gcloud-service-auth:
    required: false
    description: 'Credentials file for gcloud set up'
  project-id:
    required: true
    description: 'Google Cloud Project ID'
  deployment-name:
    required: true
    description: 'Name of the Google Cloud Project deployment'
  deployment-environment:
    required: true
    description: 'Deployment Environment (ex: test, beta, prod, ...)'
  deployment-region:
    required: false
    description: 'The region where your deployment is'
    default: 'us-central1'
  deployment-zone:
    required: false
    description: 'The zone where your deployment is'
    default: ''
  deployment-namespace:
    required: false
    description: 'Deployment Kubernetes Namespace'
    default: 'default'
  cluster-name:
    required: false
    description: 'Kubernetes Cluster where the deployments live, required if updating the deployment'
  java-version:
    required: false
    description: 'Version of Java to use'
    default: 17
  update-deployment:
    required: false
    description: 'Boolean indicating if the deployment should be updated along with the image push'
    default: 'true'
  artifactory-username:
    required: true
    description: 'The user name to access Labs Cloud artifacts from Artifactory'
  artifactory-password:
    required: true
    description: 'The password to access Labs Cloud artifacts from Artifactory'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      name: Install Java
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
        cache: 'gradle'
    - run: echo '::set-output name=IMAGE_NAME::gcr.io/${{ inputs.project-id }}/${{ inputs.deployment-name }}'
      shell: bash
      name: Generate the name of the docker image
      id: generate-image-name
    - uses: gradle/gradle-build-action@v2
      name: Install Gradle Wrapper
    - run: ./gradlew clean bootBuildImage -Partifactory_user=${{ inputs.artifactory-username }} -Partifactory_password=${{ inputs.artifactory-password }} --imageName=${{steps.generate-image-name.outputs.IMAGE_NAME}}:${{ github.sha }}
      shell: bash
      name: Run Gnag and build Docker Container
      env:
        ARTIFACTORY_USER: ${{ inputs.artifactory-username }}
        ARTIFACTORY_PASSWORD: ${{ inputs.artifactory-password }}
    - uses: 'google-github-actions/auth@v0'
      name: Login to Google Cloud
      with:
        credentials_json: ${{ inputs.gcloud-service-auth }}
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: Authorize Docker push
      shell: bash
      run: gcloud auth configure-docker
    - name: Build and Push Container
      shell: bash
      run: |-
        docker push ${{steps.generate-image-name.outputs.IMAGE_NAME}}:${{ github.sha }}
        docker tag ${{ steps.generate-image-name.outputs.IMAGE_NAME }}:${{ github.sha }} ${{ steps.generate-image-name.outputs.IMAGE_NAME }}:latest
        docker push ${{steps.generate-image-name.outputs.IMAGE_NAME}}:latest
    - name: Set GCloud region
      shell: bash
      run: |-
        gcloud config set compute/region ${{ inputs.deployment-region }}
      if: ${{ inputs.update-deployment == 'true' && inputs.deployment-zone == '' }}
    - name: Set GCloud zone
      shell: bash
      run: |-
        gcloud config set compute/zone ${{ inputs.deployment-zone }}
      if: ${{ inputs.update-deployment == 'true' && inputs.deployment-zone != '' }}
    - name: Fetch k8s cluster credentials
      shell: bash
      run: |-
        gcloud container clusters get-credentials ${{ inputs.cluster-name }}
      if: ${{ inputs.update-deployment == 'true' }}
    - name: Start the latest container
      shell: bash
      run: |-
        kubectl set image deployment "${{ inputs.deployment-name }}-${{ inputs.deployment-environment }}" "${{ inputs.deployment-name }}"="${{ steps.generate-image-name.outputs.IMAGE_NAME }}:${{ github.sha }}" --all --record=true --namespace="${{ inputs.deployment-namespace }}"
      if: ${{ inputs.update-deployment == 'true' }}
    - name: Checking deployment success status
      shell: bash
      run: |-
        kubectl rollout status deployment "${{ inputs.deployment-name }}-${{ inputs.deployment-environment }}" --timeout=5m
      if: ${{ inputs.update-deployment == 'true' }}